# permissions for end users to view covidtrackerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: covidtrackerdeployment-viewer-role
rules:
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - covidtrackerdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - covidtrackerdeployments/status
  verbs:
  - get
