# permissions for end users to view coviddata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coviddata-viewer-role
rules:
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - coviddata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - coviddata/status
  verbs:
  - get
