
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - covidtrackerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - covidtrackerdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - covid.covid.tracker.io
  resources:
  - covidtrackerdeployments/status
  verbs:
  - get
  - patch
  - update
