## Append samples you want in your CSV to this file as resources ##
resources:
- covid_v1alpha1_covidtrackerdeployment.yaml
- covid_v1alpha1_coviddata.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
